id: P006848
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4702
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད།
  author: ''
  volumes:
    0c0eb3a927c348b48a3c66dffe2ad4ef:
      image_group_id: I3CN4704
      title: ''
      volume_number: 1
      total_pages: 802
      base_file: v001.txt
