id: I44357F3A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:40:09+00:00'
last_modified: '2022-06-08T07:18:01.072055+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4702
  title: འདུལ་བ་མདོ་རྩའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5CBC:
      image_group_id: I3CN4704
      title: ''
      total_pages: 802
      order: 1
      base_file: 5CBC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
